Release 6.0.4
purestorage/pso-csi pull request #117
Opened 2020-11-25 21:11 UTC by haibinxie

- Ephemeral volume support.
- CSI 1.3 compliance.
- Support HostName using FQDN.
- Improve volume provisioning performance when topology is enabled
- Add default cockroach DB pod memory limit to 1GB
- Fix volume attach failure when active cluster is enabled.
- Fix failure when image contains port as suffix of repository.

2020-11-25 23:19 UTC, pure-jliao requested changes
we need to put the notes in CHANGELOG.md, then update all the tag versions in mirror_pso_containers.sh, pure-pso/README.md, and values.yaml, finally rerun update.sh to update the PR.

2020-11-25 23:19 UTC, pure-jliao commented on mirror_pso_containers.sh
>  purestorage/cockroach-operator:v1.0.3
update cockroach-operator and dbdeployer to v1.0.4 and k8s to v6.0.4

2020-11-25 23:19 UTC, pure-jliao commented on pure-pso/README.md
>  | purestorage/cockroach-operator           | v1.0.3  |
cockroach-operator and dbdeployer to v1.0.4

2020-11-25 23:19 UTC, pure-jliao commented on pure-pso/values.yaml
> +      tag: v1.0.2
k8s, cockroach-operator and dbdeployer need to be updated in values.yaml

2020-11-28 05:01 UTC, pure-jliao approved these changes
LGTM! don't forget to squash commits!

2020-11-29 17:42 UTC, dsupure approved these changes
LGTM!

2020-12-04 19:09 UTC, david-enli commented
just a reminder for everyone, we need to take out FQDN for now

2020-12-04 19:10 UTC, david-enli requested changes
just a reminder for us to remove the FQDN line

2020-12-09 20:33 UTC, pure-jliao reviewed
Could you help to add those in the changelog? thanks.

2020-12-09 20:33 UTC, pure-jliao commented on CHANGELOG.md
> +* Fix failure when image contains port as suffix of repository.
Fix filesystem / raw block within pod doesn't change after volume expansion.

2020-12-09 20:33 UTC, pure-jliao commented on CHANGELOG.md
> +* Add default cockroach DB pod memory limit to 1GB.
Volume expansion no longer needs pod restart.

2020-12-10 17:48 UTC, merged