Support DB topology
purestorage/pso-csi pull request #156
Opened 2021-04-01 02:55 UTC by haibinxie

2021-04-01 03:13 UTC, dsupure approved these changes
lgtm!

2021-04-01 13:18 UTC, sdodsley requested changes
Need to add this new parameter into the list in the README file.

Also, does this need to be added to the values schema file?

2021-04-02 05:30 UTC, haibinxie commented
@sdodsley resolved in a new commit.

2021-04-02 13:00 UTC, sdodsley approved these changes

2021-04-02 15:55 UTC, merged