[NSTK-2068] Docs & Example yamls for Snapshot Importing
purestorage/pso-csi pull request #86
Opened 2020-09-28 21:29 UTC by DIMPLY

Document & example yamls.

2020-09-28 21:36 UTC, david-enli commented
so for example yamls, we have a dedicated folder where other example yamls live: https://github.com/purestorage/pso-csi/tree/master/docs/examples
Might want to move your examples there

2020-09-28 22:41 UTC, david-enli commented
Looks good to me, I'll let Simon or Adam read through it.

2020-09-28 22:59 UTC, sdodsley requested changes

2020-09-28 22:59 UTC, sdodsley commented on docs/csi-snapshot-import.md
> +Importing a snapshot requires its source volume object already exists in Kubernetes. That means the volume object should either be created inside Kubernetes, or have already been imported to Kubernet
requires that the source volume

2020-09-28 22:59 UTC, sdodsley commented on docs/csi-snapshot-import.md
> +2. Make sure you have mounted the PVC to a pod. This is important because only after that, the PVC object is available to snapshotter.
because only after that is the PVC object available to the snapshotter

2020-09-28 22:59 UTC, sdodsley commented on docs/csi-snapshot-import.md
> +When you have the source volume ready as prescribed above, follow the steps below to create `VolumeSnapshotContent` and `VolumeSnapshot` objects manually:
as described above

2020-09-28 22:59 UTC, sdodsley commented on docs/csi-snapshot-import.md
> +1. Create and deploy a snapshot content object with `snapshotHandle` configured to be the **full** name of the snapshot in backend, and `volumeSnapshotRef` to be the volume snapshot at your choice.
Create and deploy a snapshotcontent object with the `snapshotHandle` configured to be the **full** name of the snapshot name on that backend, and `volumeSnapshotRef` to be a volume snapshot name of your choice.

2020-09-28 22:59 UTC, sdodsley commented on docs/csi-snapshot-import.md
> +   * With no namespace: test-backend-vol.test-backend-snapshot
Change `namespace` for something else, eg `cluster` here and the two bullet points below

2020-09-28 22:59 UTC, sdodsley commented on docs/csi-snapshot-import.md
> + In all cases, the snapshot will be imported with an empty namespace (""), and the backend namespace (also known as cluster id) will be concatenated as the prefix of the source volume name.
change backend namespace again - maybe cluster identifier??

2020-09-28 22:59 UTC, sdodsley commented on docs/csi-snapshot-import.md
> +We plan to support the following in the future:
Not sure we should be adding roadmap stuff in this document. 
Should probably remove this section

2020-09-29 17:31 UTC, sdodsley approved these changes

2020-09-29 17:34 UTC, merged